# Nombre del WorkFlow
name: Hola Mundo

# Evento: Permite activarlo manualmente desde la pestaña "Actions"
on:
  workflow_dispatch:

# Trabajos
jobs:
  # Tarea 1
  carmen:
    runs-on: ubuntu-latest # Sistema operativo virtual

    # Pasos que se ejecutan en orden
    steps:
      - name: decir-hola
        run: echo "carmen vargas"

      # Solución al Desafío 01: Desplegar la fecha del sistema
      - name: decir-fecha
        run: date
